server:
  port: 8080
  servlet:
    context-path: /



spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: qsy-test
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
#  shardingsphere:
#    # sharding-jdbc开关
#    enabled: true
#    # sharding-jdbc 数据源
#    datasource:
#      names: db0
#      db0:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
#        username: root
#        password: 123456
#    sharding:
#      #默认数据源
#      default-data-source-name: db0
#      # 分表策略
#      tables:
#        sys_user:
#          actual-data-nodes: db0.sys_user_$->{2020..2030}0$->{1..9},db0.sys_user_$->{2020..2030}$->{10..12}
#          table-strategy:
#            complex:
#              #分表字段
#              sharding-columns: id,registerTime
#              #分表算法
#              algorithm-class-name: com.test.service.shardingRuleAlgorithm.UserShardingAlgorithm
##      binding-tables: user


flowable:
  idm:
    enabled: false
  async-executor-activate: false
  common:
    app:
      security:

      role-prefix:
      idm-url: http://localhost:8080/flowable-idm
      idm-admin:
        user: admin
        password: admin
  modeler:
    app:
      rest-enabled: true
  rest:
    app:
      authentication-mode: verify-privilege